on:
  push:
    branches:
      - develop

name: Deploy preproduction

jobs:
  phpunit-test:
    name: Starting PHPUNIT test
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Composer update
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: Phpunit start
        run : composer test

  deploy-on-vps:
    name: SSH Upload
    runs-on: ubuntu-latest
    needs: phpunit-test
    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          sudo ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Repo file checkout
        uses: actions/checkout@v4

      - name: Deploy to the server
        run: |
          echo "Starting deployment..."
          
          sudo ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " echo 'start' "
          
          sudo rsync -a -v --delete --exclude='.env' ${{ github.workspace }}/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR_PREPROD }}
          
          sudo ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "chmod -R 777 ${{ secrets.WORK_DIR_PREPROD }} && cd ${{ secrets.WORK_DIR_PREPROD }} && composer update && php spark migrate"
          
          echo "Deployment completed."

      - name: clean
        run: rm -rf ~/.ssh