on:
  push:
    branch:
      - master

name: 🚀 Deploy with test

jobs:
  phpunit-test:
    name: Starting PHPUNIT test
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Composer update
        uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs

      - name: Phpunit start
        run : composer test

  deploy-on-vps:
    name: SSH Upload
    runs-on: ubuntu-latest
    needs: phpunit-test
    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Repo file checkout
        uses: actions/checkout@v4

      - name: Deploy to the server
        run: |
          echo "Starting deployment..."
          
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " rm -r ${{ secrets.WORK_DIR }} && mkdir ${{ secrets.WORK_DIR }} "
          
          scp -r ${{ github.workspace }}/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
            
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "chmod a+rwx /var/www/html/writable/cache && cd ${{ secrets.WORK_DIR }} && composer update"
        
          echo "Deployment completed."

      - name: clean
        run: rm -rf ~/.ssh


